//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FollowMe_Batch
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int OrderDetailId { get; set; }
        public Nullable<int> Amount { get; set; }
        public string FirstEPC { get; set; }
        public string LastEPC { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProcessId { get; set; }
    }
}
