//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FollowMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveAntenna
    {
        public int ActiveAntennaId { get; set; }
        public Nullable<int> ActiveAntennas { get; set; }
        public Nullable<int> ReaderId { get; set; }
    }
}
