//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FollowMe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FollowModelContainer : DbContext
    {
        public FollowModelContainer()
            : base("name=FollowModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActiveAntenna> ActiveAntenna { get; set; }
        public DbSet<ActiveOrder> ActiveOrder { get; set; }
        public DbSet<Colors> Colors { get; set; }
        public DbSet<ConnectionDetailsInStation> ConnectionDetailsInStation { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderDetails> OrderDetails { get; set; }
        public DbSet<Owners> Owners { get; set; }
        public DbSet<Process> Process { get; set; }
        public DbSet<ProcessDetails> ProcessDetails { get; set; }
        public DbSet<Readers> Readers { get; set; }
        public DbSet<Reading> Reading { get; set; }
        public DbSet<Station> Station { get; set; }
    }
}
