//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FollowMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Readers
    {
        public int ReaderId { get; set; }
        public string Area { get; set; }
        public string IP { get; set; }
        public string Name { get; set; }
    }
}
