//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Efrat.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessDetails
    {
        public int ProcessDetailId { get; set; }
        public Nullable<int> Minutes { get; set; }
        public string MoreDetails { get; set; }
        public Nullable<int> Station { get; set; }
    }
}
